# Generated by Django 4.0.6 on 2022-07-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetInTouch',
            new_name='Message',
        ),
    ]
